resolver: lts-13.13

packages:
- '.'

extra-deps:
- rss-3000.2.0.7
- scotty-tls-0.4.1
- HaXml-1.25.5

flags: {}

extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Allow a newer minor version of GHC than the snapshot specifies
compiler-check: newer-minor
